services:
  # 1. Backend Web Service
  - type: web
    name: auth-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      # - key: MONGO_URI
      #   value: mongodb+srv://...

  # 2. Frontend Static Site
  - type: web
    name: auth-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: auth-backend
          property: url
